# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - pip install .
      - export PROJ_NETWORK=TRUE
      - export PROJ_DATA="${CONDA_PREFIX}/share/proj"
      - echo -e $(ls -la ${PROJ_DATA})

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

conda:
  environment: docs/environment.yml

# python:
#   install:
#     - requirements: docs/requirements.txt

formats: all
