# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - PROJ_NETWORK=TRUE
      - echo -e "$(mamba env list)"
      - echo -e "$(ls -la /home/docs/checkouts/readthedocs.org/user_builds/silvistat/conda/78/share/proj)"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .

formats: all
