# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: SilviMetric
author: ''
#copyright: "2025"
logo: '_static/logo/silvimetric_logo.png'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: -1
  run_in_temp: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: silvimetric.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/hobuinc/silvimetric  # Online location of your book
#  path_to_book: book/  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  use_edit_page_button: true
  favicon: './_static/logo/favicon.ico'
  short_title: "Documentation"
  html_show_copyright: false
  html_short_title: SilviMetric
  html_title: SilviMetric
  extra_footer: |
    <a href="https://hobu.co/access.html"><img width="30px" src="./_static/logo/hobu-emblem-32x32.png" /></a> <a href="/copyright.html">Copyright</a> ©2025 <a href="https://github.com/kylemann16">Kyle Mann</a>, <a href="http://github.com/hobu">Howard Butler</a>, <a href="http://github.com/hobuinc">Hobu, Inc.</a>, and <a href="https://github.com/hobuinc/silvimetric/graphs/contributors">others</a>


sphinx:
  config:
    html_show_copyright: false
    latex_logo: "./_static/logo/silvimetric_logo.png"
    latex_use_parts: false
    latex_show_urls: "inline"
    latex_elements:
      preamble: '
  \makeatother
  %\color {blue}
  %\normalcolor {dark blue}
  \definecolor{VerbatimColor}{RGB}{239, 239, 239}
  \definecolor{VerbatimBorderColor}{RGB}{148, 148, 148}
  \usepackage{geometry}
   \geometry{
   letterpaper,
   left={30mm},
  }
  \raggedright'
      figure_align: 'htbp'
      releasename: ''
      tocdepth: 4
      pointsize: '12pt'
      papersize: 'letterpaper'
    pygments_style: "sphinx"
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.mathjax
    - sphinx.ext.intersphinx
    - notfound.extension

parse:
  myst_substitutions:
    ASPRSLAS: '[ASPRS LAS](https://www.asprs.org/divisions-committees/lidar-division/laser-las-file-format-exchange-activities)'
    GDAL: '[GDAL](https://gdal.org/)'
    NumPy: '[NumPy](https://numpy.org)'
    SciPy: '[SciPy](https://scipy.org)'
    "scikitlearn": '[scikit-learn](https://scikit-learn.org/stable/)'
    "scikit": '[scikit-learn](https://scikit-learn.org/stable/)'
    PyTorch: '[PyTorch](https://pytorch.org)'
    TensorFlow: '[TensorFlow](https://tensorflow.org)'
    Dask: '[Dask](https://www.dask.org)'
    TileDB: '[TileDB](https://docs.tiledb.com/main)'
    GeoTIFF: '[GeoTIFF](https://github.com/OSGeo/libgeotiff)'
    HOBU: '[Hobu](https://hobu.co/)'
    FUSION: '[FUSION](http://forsys.sefs.uw.edu/fusion/fusionlatest.html)'
    JSON: '[JSON](https://en.wikipedia.org/wiki/JSON)'
    LASzip: '[LASzip](http://laszip.org)'
    LiDAR: '[LiDAR](https://en.wikipedia.org/wiki/Lidar)'
    PCL: '[PCL](http://pointclouds.org)'
    PDAL: '[PDAL](https://pdal.io/)'
    PROJ: '[PROJ](https://proj.org)'
    S3: '[S3](https://aws.amazon.com/pm/serv-s3/)'
    CondaForge: '[CondaForge](https://conda-forge.org/docs/)'
    Conda: '[Conda](https://docs.conda.io/en/latest/)'
    Python: '[Python](https://python.org/)'
    Click: '[Click](https://click.palletsprojects.com/en/8.1.x/)'
  myst_enable_extensions:
    - substitution
    - deflist
    - dollarmath

