###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = ''
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.autodoc', 'sphinx.ext.mathjax', 'notfound.extension', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = './_static/logo/favicon.ico'
html_logo = '_static/logo/silvimetric_logo.png'
html_show_copyright = False
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': '', 'deepnote_url': ''}, 'path_to_docs': '', 'repository_url': 'https://github.com/hobuinc/silvimetric', 'repository_branch': 'main', 'extra_footer': '<a href="https://hobu.co/access.html"><img width="30px" src="./_static/logo/hobu-emblem-32x32.png" /></a> <a href="/copyright.html">Copyright</a> ©2025 <a href="https://github.com/kylemann16">Kyle Mann</a>, <a href="http://github.com/hobu">Howard Butler</a>, <a href="http://github.com/hobuinc">Hobu, Inc.</a>, and <a href="https://github.com/hobuinc/silvimetric/graphs/contributors">others</a>\n', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': '', 'plausible_analytics_domain': '', 'plausible_analytics_url': 'https://plausible.io/js/script.js'}, 'use_repository_button': True, 'use_edit_page_button': True, 'use_issues_button': True}
html_title = 'SilviMetric'
latex_elements = {'preamble': ' \\makeatother %\\color {blue} %\\normalcolor {dark blue} \\definecolor{VerbatimColor}{RGB}{239, 239, 239} \\definecolor{VerbatimBorderColor}{RGB}{148, 148, 148} \\usepackage{geometry} \\geometry{ letterpaper, left={30mm}, } \\raggedright', 'figure_align': 'htbp', 'releasename': '', 'tocdepth': 4, 'pointsize': '12pt', 'papersize': 'letterpaper'}
latex_engine = 'pdflatex'
latex_logo = './_static/logo/pdal_logo_only.png'
latex_show_urls = 'inline'
latex_use_parts = False
myst_enable_extensions = ['substitution', 'deflist', 'dollarmath']
myst_substitutions = {'ASPRSLAS': '[ASPRS LAS](https://www.asprs.org/divisions-committees/lidar-division/laser-las-file-format-exchange-activities)', 'GDAL': '[GDAL](https://gdal.org/)', 'NumPy': '[NumPy](https://numpy.org)', 'SciPy': '[SciPy](https://scipy.org)', 'scikit-learn': '[scikit-learn](https://scikit-learn.org/stable/)', 'scikit': '[scikit-learn](https://scikit-learn.org/stable/)', 'PyTorch': '[PyTorch](https://pytorch.org)', 'TensorFlow': '[TensorFlow](https://tensorflow.org)', 'Dask': '[Dask](https://www.dask.org)', 'TileDB': '[TileDB](https://docs.tiledb.com/main)', 'GeoTIFF': '[GeoTIFF](https://github.com/OSGeo/libgeotiff)', 'HOBU': '[Hobu](https://hobu.co/)', 'FUSION': '[FUSION](http://forsys.sefs.uw.edu/fusion/fusionlatest.html)', 'JSON': '[JSON](https://en.wikipedia.org/wiki/JSON)', 'LASzip': '[LASzip](http://laszip.org)', 'LiDAR': '[LiDAR](https://en.wikipedia.org/wiki/Lidar)', 'PCL': '[PCL](http://pointclouds.org)', 'PDAL': '[PDAL](https://pdal.io/)', 'PROJ': '[PROJ](https://proj.org)', 'S3': '[S3](https://aws.amazon.com/pm/serv-s3/)', 'CondaForge': '[CondaForge](https://conda-forge.org/docs/)', 'Conda': '[Conda](https://docs.conda.io/en/latest/)', 'Python': '[Python](https://python.org/)', 'Click': '[Click](https://click.palletsprojects.com/en/8.1.x/)'}
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = True
nb_execution_mode = 'cache'
nb_execution_timeout = -1
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
