name: sm-docs
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - tiledb-py
  - numpy
  - pip:
    - sphinx
    - sphinxcontrib-bibtex
    - sphinx-rtd-theme
    - sphinxcontrib-spelling
    - sphinx-notfound-page